# Generated by Django 2.2 on 2020-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdata',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='order_id',
            field=models.IntegerField(default=None),
        ),
    ]
